### PR TITLE
Add support for Hbm/Hbm2 memory device types

### PR DESCRIPTION
**Pull request by ldfsilva**
Fix https://github.com/jcreekmore/dmidecode/issues/29

### CODE REVIEW

**Review by jcreekmore — APPROVED** [review]
Looks good, but if you could rebase it so that it is only trying to merge in the one commit, I would appreciate it.

**Comment by ldfsilva** [comment]
This one is clean now, showing 1 commit.

**Comment by jcreekmore** [comment]
This is now conflicting with the previous PR I merged. If you can rebase and fix that up, you will be golden.

**Comment by ldfsilva** [comment]
thanks for the quick response, merge conflict resolved.

**Comment by ldfsilva** [comment]
When you get a chance if you could issue a new release version with the latest additions, that'd be perfect.

**Review by jcreekmore — APPROVED** [review]

**Comment by jcreekmore** [comment]
> When you get a chance if you could issue a new release version with the latest additions, that'd be perfect.

That is going to have to wait until Monday. I'm away from the computer that has my keys on it until then (the GitHub app works great on mobile, but I don't have a good workflow for cargo releases on mobile yet). I will make a note to do it when I get home, though.

**Comment by jcreekmore** [comment]
@ldfsilva I released 0.7.5 a few minutes ago.

**Comment by ldfsilva** [comment]
That's great, thank you @jcreekmore

**Pull request merged**
