### PR TITLE
Add support for Ddr5/LpDdr5 memory device types

### PR DESCRIPTION
**Pull request by ldfsilva**
Fix issue https://github.com/jcreekmore/dmidecode/issues/27

### CODE REVIEW

**Comment by ldfsilva** [comment]
>  ldfsilva wants to merge 14 commits into jcreekmore

I'm not sure why github shows previous commits when they were already merged, I'll look this up. Let me know if you know/wish me to modify the PR @jcreekmore  and I'll do so.

**Comment by jcreekmore** [comment]
Yeah, if you could rebase your branch on top of my master branch, that should cause that to go away.

**Review by jcreekmore — APPROVED** [review]
Other than a rebase to clean up the history, I think this looks good.

**Comment by ldfsilva** [comment]
rebased, looks clean now with 1 commit.

**Review by jcreekmore — APPROVED** [review]

**Pull request merged**
