### PR TITLE
Fix processor family parsing for smbios 2.6 and 2.8 when family is 8 bytes

### PR DESCRIPTION
**Pull request by ldfsilva**
Fix issue #23, I'm putting this out for discussion as an applicable fix for the invalid processor family parsing error.

Both [smbios 2.8](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_2.8.0.pdf) (page 48) and [smbios 3.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.0.0.pdf) (page 50) spec informs that:

> FEh 254 Indicator to obtain the processor family from the Processor Family 2 field

In that case the approach taken here is to check whether __Processor Family__ (`06h`) indicates that __Processor Family 2__ needs to be consulted or not prior to attempting covering that field directly as some times as the one reproted in issue #23 the value can just be `0x00 0x00`, triggering the invalid parsing.

### CODE REVIEW

**Comment by ldfsilva** [comment]
incorporated [feedback](https://github.com/jcreekmore/dmidecode/pull/24#pullrequestreview-895244735) in [6339a24](https://github.com/jcreekmore/dmidecode/pull/24/commits/6339a24f5469b9ac29088e2f9c5e3dc6dfc7abf8).

**Comment by jcreekmore** [comment]
For some reason it wasn't merging in cleanly, so I cherry-picked the commit into master.

**Comment by ldfsilva** [comment]
awesome, thank you! Would you be able to bump the version shortly to reflect the latest fixes?

**Comment by jcreekmore** [comment]
Just released v0.7.4 for you.

**Pull request closed without merging**
